
    set(CLUCENE_VERSION_MAJOR 2)
    set(CLUCENE_VERSION_MINOR 3)
    set(CLUCENE_VERSION_REVISION 3)
    set(CLUCENE_VERSION_PATCH 4)
    
    set(CLUCENE_VERSION 2.3.3.4)
    set(CLUCENE_SOVERSION 1)
